# This workflow compiles the resume from source and commits it to the main branch.
name: 'Compile Resume'

on:
  push:
  schedule:
  - cron: '0 5 * * *'

jobs:
  compile-resume:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Compile LaTeX Resume Source
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            Resume.tex
      - name: Commit Updated Resume.pdf
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          commit_message: Update resume
          file_pattern: Resume.pdf
